FOODSTATION/Models/Country.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace FOODSTATION.Models
{
    public class Country
    {
        public int Id { get; set; }

        [Required]
        [DisplayName("اسم الدولة")]
        public string Name { get; set; }

        public virtual ICollection<Region> Regions { get; set; }
    }
}

FOODSTATION/Controllers/CountriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FOODSTATION.Models;

namespace FOODSTATION.Controllers
{
    [Authorize(Roles = "Admin")]
    public class CountriesController : Controller
    {
        private readonly ApplicationDbContext db;

        public CountriesController(ApplicationDbContext _db)
        {
            db = _db;
        }

        // GET: Countries
        public ActionResult CountryDashboard()
        {
            ViewBag.Countries = db.Countries.ToList(); 
            return View();
        }

        public PartialViewResult Refreash()
        {
            var Countries = db.Countries.ToList();
            ViewBag.Countries = Countries;
            return PartialView("_CountryPartial", Countries);
        }

        // POST: Countries/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        //[ValidateAntiForgeryToken] 
        public JsonResult Create(Country country)
        {
            var result = false;
            if (ModelState.IsValid)
            {
                db.Countries.Add(country);
                db.SaveChanges();
                result = true;
                return Json(result, JsonRequestBehavior.AllowGet);
            }

            return Json(result, JsonRequestBehavior.AllowGet);
        }

        // POST: Countries/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public JsonResult Edit(Country country)
        {
            if (ModelState.IsValid)
            {
                db.Entry(country).State = EntityState.Modified;
                db.SaveChanges();
                return Json(true, JsonRequestBehavior.AllowGet);
            }

            return Json(false, JsonRequestBehavior.AllowGet);
        }

        // POST: Restaurants/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        public JsonResult DeleteConfirmed(int id)
        {
            var message = "";
            var country = db.Countries.Find(id);
            var regions = db.Regions.ToList().Where(x => x.CountryId == country.Id);
            if (regions.Count() > 0)
            {
                message = "haveItem";
                return Json(message, JsonRequestBehavior.AllowGet);
            }

            if (country == null)
            {
                message = "لايوجد مطعم بالمعرف المرسل الى السرفر";
                return Json(message, JsonRequestBehavior.AllowGet);
            }

            db.Countries.Remove(country);
            db.SaveChanges();

            return Json(message, JsonRequestBehavior.AllowGet);
        }


        // POST: Countries/DeletewithItems/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        public ActionResult DeleteCountryAndRegions(int id)
        {
            var country = db.Countries.Find(id);
            var regions = db.Regions.ToList().Where(x => x.CountryId == country.Id);

            foreach (var region in regions)
            {
                var restaurants = db.Restaurants.ToList().Where(x => x.RegionId == region.Id);

                if (restaurants.Count() > 0)
                {
                    foreach (var restaurant in restaurants)
                    {
                        var items = db.Items.ToList().Where(x => x.RestaurantId == restaurant.Id);

                        if (items.Count() > 0)
                        {
                            foreach (var item in items)
                            {
                                string itemOldPath = Path.Combine(Server.MapPath("~/Uploads/Items/"), item.ImgUrl);
                                System.IO.File.Delete(itemOldPath);
                                db.Items.Remove(item);
                            }
                        }
                        string restaurantOldPath = Path.Combine(Server.MapPath("~/Uploads/Restaurants/"), restaurant.ImgUrl);
                        System.IO.File.Delete(restaurantOldPath);
                        db.Restaurants.Remove(restaurant);
                    }
                }
                db.Regions.Remove(region);
            }
            db.Countries.Remove(country);
            db.SaveChanges();

            return Json(true, JsonRequestBehavior.AllowGet);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FOODSTATION/Controllers/ItemsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using Microsoft.AspNet.Identity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FOODSTATION.Models;
using FOODSTATION.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace FOODSTATION.Controllers
{
    [Authorize(Roles = "Admin , RestaurantOwner")]

    public class ItemsController : Controller
    {
        private readonly ApplicationDbContext db;

        public ItemsController(ApplicationDbContext _db)
        {
            db = _db;
        }

        // GET: Items
        public ActionResult ItemDashboard()
        {
            var userId=User.Identity.GetUserId();
            if (User.IsInRole("RestaurantOwner"))
            {
                var items = db.Items.ToList().Where(x=>x.Restaurant.UserId== userId);   
                ViewBag.items = items;
                ViewBag.CategoryId = new SelectList(db.Categories.ToList(), "Id", "Name");
                ViewBag.RestaurantId = new SelectList(db.Restaurants.ToList().Where(x => x.UserId == userId), "Id", "Name");
                return View();
            }
            else
            {
                var items = db.Items.ToList();
                ViewBag.items = items;
                ViewBag.CategoryId = new SelectList(db.Categories.ToList(), "Id", "Name");
                ViewBag.RestaurantId = new SelectList(db.Restaurants.ToList(), "Id", "Name");
                return View();
            }
            
        }

        public PartialViewResult Refreash()
        {
            if (User.IsInRole("RestaurantOwner"))
            {
                var items = db.Items.ToList().Where(x => x.Restaurant.UserId == User.Identity.GetUserId());
                ViewBag.items = items;
                ViewBag.CategoryId = new SelectList(db.Categories.ToList(), "Id", "Name");
                ViewBag.RestaurantId = new SelectList(db.Restaurants.ToList().Where(x => x.UserId == User.Identity.GetUserId()), "Id", "Name");
                return PartialView("_ItemPartial", items);
            }
            else
            {
                var items = db.Items.ToList();
                ViewBag.items = items;
                ViewBag.CategoryId = new SelectList(db.Categories.ToList(), "Id", "Name");
                ViewBag.RestaurantId = new SelectList(db.Restaurants.ToList(), "Id", "Name");
                return PartialView("_ItemPartial", items);
            }
        }

        public JsonResult IsImageExist(string upload)
        {
            var Message = "";
             
                string path = Path.Combine(Server.MapPath("~/Uploads/Items/"), upload);
                if (System.IO.File.Exists(path))
                {
                    Message = "الصورة التي قمت بتحديها موجودة بالفعل لعنصر أخر قم بأختيار صورة مختلفة";

                return Json(Message, JsonRequestBehavior.AllowGet); 
                }
                else

                return Json(Message, JsonRequestBehavior.AllowGet);         
        }

        // POST: Items/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        //[ValidateAntiForgeryToken] 
        public JsonResult Create(Item item, HttpPostedFileBase upload)
        {
            var result = false;
            if (ModelState.IsValid)
            {
                string path = Path.Combine(Server.MapPath("~/Uploads/Items/"), upload.FileName);
                upload.SaveAs(path);
                item.ImgUrl = upload.FileName;
                db.Items.Add(item);
                db.SaveChanges();
                result = true;    
                return Json(result, JsonRequestBehavior.AllowGet);
            }

            return Json(result, JsonRequestBehavior.AllowGet);
        }

        // POST: Items/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public JsonResult Edit(Item item, HttpPostedFileBase upload)
        {
            if (ModelState.IsValid)
            {
                string oldPath = Path.Combine(Server.MapPath("~/Uploads/Items"), item.ImgUrl);

                if (upload != null)
                {
                    System.IO.File.Delete(oldPath);
                    string path = Path.Combine(Server.MapPath("~/Uploads/Items"), upload.FileName);
                    upload.SaveAs(path);
                    item.ImgUrl = upload.FileName;
                }
                db.Entry(item).State = EntityState.Modified;
                db.SaveChanges();
                return Json(true, JsonRequestBehavior.AllowGet);
            }

            ViewBag.CategoryId = new SelectList(db.Categories.ToList(), "Id", "Name", item.CategoryId);
            ViewBag.RestaurantId = new SelectList(db.Restaurants.ToList(), "Id", "Name", item.RestaurantId);
            return Json(false, JsonRequestBehavior.AllowGet);
        }

        // GET: Items/Edit/5
        public ActionResult GetItem(int? id)
        {   
           var item = db.Items.Find(id);
            ItemVM itemVM = new ItemVM();
            if (item != null)
            {                  
                itemVM.Name = item.Name;
                itemVM.Price = item.Price;
                itemVM.TimeOfDone = item.TimeOfDone.ToString();
                itemVM.Restaurant = item.Restaurant.Name;
                itemVM.ImgUrl = item.ImgUrl;
                itemVM.Category = item.Category.Name;
                itemVM.CategoryId = item.CategoryId;
                itemVM.RestaurantId = item.RestaurantId;
            }
            return Json(itemVM ,JsonRequestBehavior.AllowGet);
        }

        // POST: Items/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        public JsonResult DeleteConfirmed(int id)
        {
            bool result = false;
            var item = db.Items.Find(id);
            if(item != null)
            {
                result = true;  
                string OldPath = Path.Combine(Server.MapPath("~/Uploads/Items/"), item.ImgUrl);
                System.IO.File.Delete(OldPath);
                db.Items.Remove(item);
                db.SaveChanges();
            }
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FOODSTATION/Views/Countries/CountryDashboard.cshtml
@model FOODSTATION.Models.Country
@{
    ViewBag.Title = "Country dashboard";
}
<div class="searshInput" style="direction:rtl">
    <input type="text" id="myInput" onkeyup="Searsh('countryTable')" placeholder="أدخل أسم للبحث ...">
    <i class="fa-solid fa-magnifying-glass"></i>
</div>

<div class="container" id="_CountryPartial" style="direction:rtl">
    @Html.Partial("_CountryPartial")
</div>

<!--Create Country-->

<div class="modal fade Country" id="Modal-countryCreate">
    <div class="modal-dialog">
        <div class="modalContent">
            <div class="modal-header">
                <h2 class="modal-title">أضافة دولة</h2>
            </div>
            <div class="modal-body">
                @using (Html.BeginForm("Create", "Countries", FormMethod.Post, new { enctype = "multipart/form-data", @id = "CreateCountryForm" }))
                {
                    @Html.AntiForgeryToken()
                    <div class="form-horizontal" style="margin-top:20px">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="form-group">
                            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-4", @style = "float:right" })
                            <div class="col-md-8">
                                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "input-fild", @id = "CCname" } })
                            </div>
                        </div>
                    </div>
                }
            </div>
            <div class="modal-footer">
                <input value="أضافة" class="btn btn-success modal-BtnCreate" id="btnCreateCountry" />
                <button id="btnCreateColse" type="button" class="btn modal-BtnClose" data-dismiss="modal" onclick="resetFilds('CreateCountryForm','',event)">أغلاق</button>
            </div>
        </div>
    </div>
</div>

<!--Edit Country-->

<div class="modal fade Country" id="Modal-countryEdit">
    <div class="modal-dialog modalCenter">
        <div class="modalContent">
            <div class="modal-header">
                <h2 class="modal-title" style="text-align:center">تعديل بيانات الدولة</h2>
            </div>
            <div class="modal-body">
                @using (Html.BeginForm("Edit", "Items", FormMethod.Post, new { enctype = "multipart/form-data", @id = "EditCountryForm" }))
                {
                    @Html.AntiForgeryToken()
                    <input type="hidden" name="Id" id="hiddenId" />
                    <div class="form-horizontal" style="margin-top:20px">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="form-group">
                            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-4", @style = "float:right" })
                            <div class="col-md-8">
                                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "input-fild", @id = "ECname" } })
                            </div>
                        </div>
                    </div>
                }
            </div>

            <div class="modal-footer">
                <input value="تعديل" class="btn btn-primary modal-BtnCreate" id="btnEditCountry" />
                <button id="btnEditColse" type="button" class="btn modal-BtnClose" data-dismiss="modal" onclick="CresetFilds(event)">أغلاق</button>
            </div>

        </div>
    </div>
</div>

FOODSTATION/Views/Countries/_CountryPartial.cshtml
<div>
    <h2>قائمة الدول</h2>
</div>

<div>
    <p>
        <a href="#" class="btn btn-primary" data-toggle="modal" data-target="#Modal-countryCreate">أضافة دولة</a>
    </p>
</div>

<table class="table" id="countryTable">
    <tr class="btn-primary">
        <th>
            أسم الدولة
        </th>
        <th></th>
    </tr>

    @foreach (var item in ViewBag.Countries)
    {
        <tr>
            <td>
                @item.Name
                <input id="CountryName+@item.Id" type="hidden" value="@item.Name" />
            </td>
            <td>
                <a style="font-size:20px" onclick="EditCountryConfirm(@item.Id)"><i class="fa-solid fa-pen-to-square Action-Icon" style="color: #005eff;"></i></a> |
                <a style="font-size:20px" onclick="DeleteCountryConfirm(@item.Id)"><i class="fa-solid fa-trash-can Action-Icon" style="color: #ff2600;"></i></a>
                <input type="hidden" id="CountryId" />
            </td>
        </tr>
    }

</table>