FOODSTATION/Models/Advertisement.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace FOODSTATION.Models
{
    public class Advertisement
    {
        public int Id { get; set; }

        public string Description { get; set; }

        public string ImgUrl { get; set; }

        public int RestaurantId { get; set; }

        public virtual Restaurant Restaurant { get; set; }
    }
}

FOODSTATION/Controllers/AdvertisementsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FOODSTATION.Models;
using FOODSTATION.Models.ViewModels;
using Microsoft.AspNet.Identity;

namespace FOODSTATION.Controllers
{
    [Authorize(Roles = "Admin , RestaurantOwner")]

    public class AdvertisementsController : Controller
    {
        private readonly ApplicationDbContext db;

        public AdvertisementsController(ApplicationDbContext _db)
        {
            db = _db;
        }

        // GET: Advertisements
        public ActionResult AdvertisementDashboard()
        {
            if (User.IsInRole("RestaurantOwner"))
            {
                var userId = User.Identity.GetUserId();

                ViewBag.Advertisements = db.Advertisements.Where(x => x.Restaurant.UserId == userId ).ToList();

                ViewBag.RestaurantId = new SelectList(db.Restaurants.Where(x =>x.UserId==userId).ToList(), "Id", "Name");
            }

            else
            {
                ViewBag.Advertisements = db.Advertisements.ToList();

                ViewBag.RestaurantId = new SelectList(db.Restaurants.ToList() , "Id", "Name");
            }

            return View();
        }

        public PartialViewResult Refreash()
        {
            if (User.IsInRole("RestaurantOwner"))
            {
                var userId = User.Identity.GetUserId();

                var Advertisements = db.Advertisements.Where(x => x.Restaurant.UserId == userId).ToList();

                ViewBag.Advertisements = Advertisements;

                ViewBag.RestaurantId = new SelectList(db.Restaurants.Where(x => x.UserId == userId).ToList(), "Id", "Name");

                return PartialView("_AdvertisementPartial", Advertisements);
            }

            else
            {
                var advertisements = db.Advertisements.ToList();

                ViewBag.Advertisements = advertisements;

                ViewBag.RestaurantId = new SelectList(db.Restaurants.ToList(), "Id", "Name");

                return PartialView("_AdvertisementPartial", advertisements);
            }
        }

        public JsonResult IsImageExist(string upload)
        {
            var Message = "";

            string path = Path.Combine(Server.MapPath("~/Uploads/Advertisements/"), upload);
            if (System.IO.File.Exists(path))
            {
                Message = "الصورة التي قمت بتحديها موجودة بالفعل لعنصر أخر قم بأختيار صورة مختلفة";

                return Json(Message, JsonRequestBehavior.AllowGet);
            }
            else

                return Json(Message, JsonRequestBehavior.AllowGet);
        }


        // POST: Advertisements/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        //[ValidateAntiForgeryToken] 
        public JsonResult Create(Advertisement adv, HttpPostedFileBase upload)
        {
            var responce = new AdvertisementResponceViewModel();
            responce.Remaing = ReminingAdeverCounter(adv.RestaurantId);

            if (ModelState.IsValid)
            { 
                if(responce.Remaing <= 0)
                {
                    responce.Message = "تعديت الحد المسموح من الأعلانات في الأشتراك ";
                    responce.Seccess = false;
                    return Json(responce, JsonRequestBehavior.AllowGet);
                }

                string path = Path.Combine(Server.MapPath("~/Uploads/Advertisements/"), upload.FileName);
                upload.SaveAs(path);
                adv.ImgUrl = upload.FileName;
                db.Advertisements.Add(adv);
                db.SaveChanges();

                responce.Remaing = ReminingAdeverCounter(adv.RestaurantId);
                responce.Message = "من الأعلانات ( "+responce.Remaing+" ) تمت الأضافة المتبقي ";
                responce.Seccess = true;

                return Json(responce , JsonRequestBehavior.AllowGet);
            }

            responce.Message =  "حدث خطأما أثناء عملية الأضافة تاكد من أدخال الحقول بالشكل الصحيح وحاول مرة أخرى";
            responce.Seccess = false;

            return Json(responce, JsonRequestBehavior.AllowGet);
        }

        public int ReminingAdeverCounter(int RestaurantId)
        {
            // NumOfAllAdv ---> Number of Allowed Advertisements in Restaurant Participations

            var NumOfAllAdv = db.Restaurants.Where(x => x.Id == RestaurantId).FirstOrDefault().Participations.Last()
                .Features.Where(x => x.Name == "Advertisement").FirstOrDefault().Numb;

            // NumOfAllAdv ---> Number of Advertisements for Restaurant 

            var NumOfAdv = db.Restaurants.Where(x => x.Id == RestaurantId).FirstOrDefault().Advertisements.Count();

            var remaining = NumOfAllAdv - NumOfAdv;

            return remaining;
        }


        public ActionResult GetAdvertisement(int? id)
        {
            var Advertisement = db.Advertisements.Find(id);
            EditAdvertisementViewModel AdvertisementVM = new EditAdvertisementViewModel();
            if (Advertisement != null)
            {
                AdvertisementVM.Description = Advertisement.Description;
                AdvertisementVM.RestaurantId = Advertisement.RestaurantId;
                AdvertisementVM.ImgUrl = Advertisement.ImgUrl;
            }
            return Json(AdvertisementVM, JsonRequestBehavior.AllowGet);
        }

        // POST: Advertisement/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public JsonResult Edit(Advertisement advertisement, HttpPostedFileBase upload)
        {
            if (ModelState.IsValid)
            {
                string oldPath = Path.Combine(Server.MapPath("~/Uploads/Advertisements"), advertisement.ImgUrl);

                if (upload != null)
                {
                    System.IO.File.Delete(oldPath);
                    string path = Path.Combine(Server.MapPath("~/Uploads/Advertisements"), upload.FileName);
                    upload.SaveAs(path);
                    advertisement.ImgUrl = upload.FileName;
                }
                db.Entry(advertisement).State = EntityState.Modified;
                db.SaveChanges();
                return Json(true, JsonRequestBehavior.AllowGet);
            }

            return Json(false, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult DeleteConfirmed(int id)
        {
            var Advertisement = db.Advertisements.Find(id);
            var responce = new AdvertisementResponceViewModel();

            if (Advertisement != null)
            {             
                string OldPath = Path.Combine(Server.MapPath("~/Uploads/Advertisements/"), Advertisement.ImgUrl);
                System.IO.File.Delete(OldPath);
                db.Advertisements.Remove(Advertisement);
                db.SaveChanges();   
                responce.Remaing = ReminingAdeverCounter(Advertisement.RestaurantId);
                responce.Seccess = true;
                responce.Message = "من الإعلانات ( " + responce.Remaing + " ) تمت عملية الحذف المتبقي";
            }
            return Json(responce, JsonRequestBehavior.AllowGet);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FOODSTATION/Views/Advertisements/AdvertisementDashboard.cshtml
@model FOODSTATION.Models.Advertisement
@{
    ViewBag.Title = "AdvertisementDashboard";
}

<div class="container" id="_AdvertisementPartial" style="direction:rtl">
    @Html.Partial("_AdvertisementPartial")
</div>

<!--Create Adv -->

<div class="modal fade Adv" id="Modal-AdvCreate">
    <div class="modal-dialog">
        <div class="modalContent">
            <div class="modal-header">
                <h2 class="modal-title" style="text-align:center">بيانات الأعلان</h2>
            </div>
            <div class="modal-body">
                @using (Html.BeginForm("Create", "Advertisements", FormMethod.Post, new { enctype = "multipart/form-data", @id = "CreateAdvForm" }))
                {
                    @Html.AntiForgeryToken()
                    <div class="row">
                        <div class="form-horizontal">

                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                                <div class="form-group">
                                    <img id="CAdvimgUrl" class="modal-Img" alt="أضف صورة">
                                    <label for="CAdvpicture" class="btn btn-primary modal-Btn">أضافة صورة</label>
                                    <input id="CAdvpicture" class="modal-filein" type="file" name="upload" onchange="loadFile('CAdvimgUrl',event)" />
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.Description,"الوصف", htmlAttributes: new { @class = "control-label col-md-4", @style = "float:right" })
                                    <div class="col-md-8" style="float:right">
                                        @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "input-fild", @id = "CAdvDescription" } })
                                        @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                                    </div>
                                </div>


                                <div class="form-group">
                                    @Html.LabelFor(model => model.RestaurantId, "أسم المطعم", htmlAttributes: new { @class = "control-label col-md-4", @style = "float:right" })
                                    <div class="col-md-8" style="float:right">
                                        @Html.DropDownList("RestaurantId", null, htmlAttributes: new { @class = "input-fild", @id = "CAdvRestaurant" })
                                        @Html.ValidationMessageFor(model => model.RestaurantId, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                        </div>
                    </div>
                }

            </div>
            <div class="modal-footer">
                <div class="form-group">
                        <input value="أضافة" class="btn btn-success modal-BtnCreate" id="btnAdvCreate" />
                        <button id="btnCreateColse" type="button" class="btn modal-BtnClose" data-dismiss="modal" onclick="resetFilds('CreateAdvForm','CAdvimgUrl',event)">أغلاق</button>
                </div>
            </div>
        </div>
    </div>
</div>


<!-- Edit Adv -->

<div class="modal fade Adv" id="Modal-AdvEdit">
    <div class="modal-dialog modalCenter">
        <div class="modalContent">
            <div class="modal-header">
                <h2 class="modal-title" style="text-align:center">بيانات الأعلان</h2>
            </div>
            <div class="modal-body">
                @using (Html.BeginForm("Edit", "Advertisements", FormMethod.Post, new { enctype = "multipart/form-data", @id = "EditAdvForm" }))
                {
                    @Html.AntiForgeryToken()
                    <div class="row">
                        <div class="form-horizontal">

                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                            <input type="hidden" name="Id" id="hiddenId" />
                            <input type="hidden" name="ImgUrl" id="hiddenImgUrl" />

                            <div class="form-group">
                                <img id="EAdvimgUrl" class="modal-Img" alt="أضف صورة">
                                <label for="EAdvpicture" class="btn btn-primary modal-Btn">أضافة صورة</label>
                                <input id="EAdvpicture" class="modal-filein" type="file" name="upload" onchange="loadFile('EAdvimgUrl',event)" />
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Description, "الوصف", htmlAttributes: new { @class = "control-label col-md-4", @style = "float:right" })
                                <div class="col-md-8" style="float:right">
                                    @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "input-fild", @id = "EAdvDescription" } })
                                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                                </div>
                            </div>


                            <div class="form-group">
                                @Html.LabelFor(model => model.RestaurantId, "أسم المطعم", htmlAttributes: new { @class = "control-label col-md-4", @style = "float:right" })
                                <div class="col-md-8" style="float:right">
                                    @Html.DropDownList("RestaurantId", null, htmlAttributes: new { @class = "input-fild", @id = "EAdvRestaurant" })
                                    @Html.ValidationMessageFor(model => model.RestaurantId, "", new { @class = "text-danger" })
                                </div>
                            </div>

                        </div>
                    </div>
                }

            </div>
            <div class="modal-footer">
                <div class="form-group">
                    <input value="تعديل" class="btn btn-success modal-BtnCreate" id="btnAdvEdit" />
                    <button id="btnEditColse" type="button" class="btn modal-BtnClose" data-dismiss="modal">أغلاق</button>
                </div>
            </div>
        </div>
    </div>
</div>

FOODSTATION/Views/Advertisements/_AdvertisementPartial.cshtml
<div>
    <h2>الأعلانات</h2>
</div>
<div>
    <p>
        <a href="#" class="btn btn-primary" data-toggle="modal" data-target="#Modal-AdvCreate">أضافة أعلان</a>
    </p>
</div>
<table class="table">
    <tr class="btn-primary">

        <th>
            الصورة
        </th>
        <th>
            الوصف
        </th>
        <th>
            المطعم
        </th>
        <th>
            الأجراء
        </th>
    </tr>

    @foreach (var item in ViewBag.Advertisements)
    {
        <tr>
            <td>
                <img src="~/Uploads/Advertisements/@item.ImgUrl" class="img-thumbnail" style="width:48px;height:48px" />
            </td>
            <td>
                @item.Description
            </td>
            <td>
                @item.Restaurant.Name
            </td>
            <td>
                <a style="font-size:20px" onclick="EditAdvConfirm(@item.Id)"><i class="fa-solid fa-pen-to-square Action-Icon" style="color: #005eff;"></i></a> |
                <a style="font-size:20px" onclick="DeleteAdvConfirm(@item.Id)"><i class="fa-solid fa-trash-can Action-Icon" style="color: #ff2600;"></i></a>
                <input type="hidden" id="AdvId" />
            </td>
        </tr>
    }

</table>