FOODSTATION/Controllers/ManageAccountController.cs
using System;
using System.Globalization;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;
using System.Threading.Tasks;
using System.Linq;
using System.Security.Claims;
using System.Web;
using System.Web.Mvc;
using FOODSTATION.Models;
using System.Data.Entity;
using FOODSTATION.Models.ViewModels;
using System.IO;

namespace FOODSTATION.Controllers
{
    public class ManageAccountController : Controller
    {
        private ApplicationSignInManager _signInManager;
        private ApplicationUserManager _userManager;
        //private ApplicationRoleManager _roleManager;
        private ApplicationDbContext db;

        public ManageAccountController()
        {
            db = new ApplicationDbContext();
        }

        public ManageAccountController(ApplicationUserManager userManager, ApplicationSignInManager signInManager)
        {
            UserManager = userManager;
            SignInManager = signInManager;
        }
        public ApplicationSignInManager SignInManager
        {
            get
            {
                return _signInManager ?? HttpContext.GetOwinContext().Get<ApplicationSignInManager>();
            }
            private set
            {
                _signInManager = value;
            }
        }

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        public ActionResult UserDashboard()
        {
            var users = UserManager.Users.ToList().Select(u => new UserVM
            {
                Id = u.Id,  
                UserName = u.UserName,
                Email = u.Email,
                PhoneNumber = u.PhoneNumber,
                Role = string.Join(", ", UserManager.GetRolesAsync(u.Id).Result)
            }).ToList();

            ViewBag.Users = users;  

            var roleManager = new RoleManager<IdentityRole>(new RoleStore<IdentityRole>(new ApplicationDbContext()));
            var roles = roleManager.Roles.Select(r => new SelectListItem { Value = r.Name, Text = r.Name }).ToList();
            ViewBag.Roles = roles;

            return View();
        }

        public PartialViewResult Refreash()
        {
            var users = UserManager.Users.ToList().Select(u => new UserVM
            {
                Id = u.Id,
                UserName = u.UserName,
                Email = u.Email,
                PhoneNumber = u.PhoneNumber,
                Role = string.Join(", ", UserManager.GetRolesAsync(u.Id).Result)
            }).ToList();

            ViewBag.Users = users;

            var roleManager = new RoleManager<IdentityRole>(new RoleStore<IdentityRole>(new ApplicationDbContext()));
            var roles = roleManager.Roles.Select(r => new SelectListItem { Value = r.Name, Text = r.Name }).ToList();
            ViewBag.Roles = roles;

            return PartialView("_UserPartial", users);
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> AddNewUser(UserVM model)
        {
            model.RegistrationInValid = "true";

            if (ModelState.IsValid)
            {
                var user = new ApplicationUser { UserName = model.UserName, Email = model.Email, PhoneNumber = model.PhoneNumber };
                var result = await UserManager.CreateAsync(user, model.Password);
                if (result.Succeeded)
                {
                    await UserManager.AddToRoleAsync(user.Id,model.Role);
                    model.RegistrationInValid = "";
                    var returnedRoleManager = new RoleManager<IdentityRole>(new RoleStore<IdentityRole>(new ApplicationDbContext()));
                    var returnedRole = returnedRoleManager.Roles.Select(r => new SelectListItem { Value = r.Name, Text = r.Name }).ToList();
                    ViewBag.Roles = returnedRole;
                    return PartialView("_AddUser", model);
                }
                AddErrors(result);
            }
            var roleManager = new RoleManager<IdentityRole>(new RoleStore<IdentityRole>(new ApplicationDbContext()));
            var roles = roleManager.Roles.Select(r => new SelectListItem { Value = r.Name, Text = r.Name }).ToList();
            ViewBag.Roles = roles;
            // If we got this far, something failed, redisplay form
            return PartialView("_AddUser", model);
        }

        public async Task<ActionResult> GetUser(string id)
        {
            var user = await UserManager.FindByIdAsync(id);
            if (user != null)
            {
                var roles = await UserManager.GetRolesAsync(user.Id);
                var updatedUser = new UserVM
                {
                    UserName = user.UserName,
                    Email = user.Email,
                    PhoneNumber = user.PhoneNumber,                  
                    Role = roles.Last(),
            };
                return Json(updatedUser, JsonRequestBehavior.AllowGet);
            }

            return HttpNotFound();
        }

        // Edit a user
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> EditUser(UserVM model)
        {
            model.RegistrationInValid = "true";

            if (ModelState.IsValid)
            {
                var user = await UserManager.FindByIdAsync(model.Id);
                if (user == null)
                {
                    return HttpNotFound();
                }
                user.Email = model.Email;
                user.UserName = model.UserName; 
                user.PhoneNumber= model.PhoneNumber;    
                var result = await UserManager.UpdateAsync(user);
                if (result.Succeeded)
                {
                    var Userroles = await UserManager.GetRolesAsync(user.Id);
                    foreach(var role in Userroles)
                    {
                        await UserManager.RemoveFromRoleAsync(user.Id, role);
                    }
                    await UserManager.AddToRoleAsync(user.Id, model.Role);
                    model.RegistrationInValid = "";
                    var returnedRoleManager = new RoleManager<IdentityRole>(new RoleStore<IdentityRole>(new ApplicationDbContext()));
                    var returnedRole = returnedRoleManager.Roles.Select(r => new SelectListItem { Value = r.Name, Text = r.Name }).ToList();
                    ViewBag.Roles = returnedRole;
                    return PartialView("_EditUser", model);

                }
                AddErrors(result);
            }
            var roleManager = new RoleManager<IdentityRole>(new RoleStore<IdentityRole>(new ApplicationDbContext()));
            var roles = roleManager.Roles.Select(r => new SelectListItem { Value = r.Name, Text = r.Name }).ToList();
            ViewBag.Roles = roles;
            // If we got this far, something failed, redisplay form
            return PartialView("_EditUser", model);
        }

        // Delete a user
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteUser(string id)
        {
            var message = "";
            var user = await UserManager.FindByIdAsync(id);
            if (user == null)
            {
                message = "لايوجد مستخدم بالمعرف المرسل الى السرفر";
                return Json(message, JsonRequestBehavior.AllowGet);
            }
            var restaurants = db.Restaurants.Where(x => x.UserId == user.Id);
            if (restaurants.Count() > 0)
            {
                message = "haveRestaurant";
                return Json(message, JsonRequestBehavior.AllowGet);
            }
            var bills = db.Bills.Where(x => x.UserId == user.Id);
            if (bills.Count() > 0)
            {
                message = "haveBills";
                return Json(message, JsonRequestBehavior.AllowGet);
            }
            var result = await UserManager.DeleteAsync(user);
            if (result.Succeeded)
            {
                return Json(message, JsonRequestBehavior.AllowGet);
            }
            AddErrors(result);
            return View("Error");
        }

        // Delete a user
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteUserAndRestaurants(string id)
        {

            var user = await UserManager.FindByIdAsync(id);

            var restaurants = db.Restaurants.Where(x => x.UserId == user.Id).ToList();
            foreach (var restaurant in restaurants)
            {
                var items = db.Items.Where(x => x.RestaurantId == restaurant.Id).ToList();
                
                if (items.Count() > 0)
                {
                    foreach (var item in items)
                    {
                        string itemOldPath = Path.Combine(Server.MapPath("~/Uploads/Items/"), item.ImgUrl);
                        System.IO.File.Delete(itemOldPath);
                        db.Items.Remove(item);
                    }
                }
                string restaurantOldPath = Path.Combine(Server.MapPath("~/Uploads/Restaurants/"), restaurant.ImgUrl);
                System.IO.File.Delete(restaurantOldPath);
                db.Restaurants.Remove(restaurant);
                db.SaveChanges();
            }

            var result = await UserManager.DeleteAsync(user);
            if (result.Succeeded)
            {
                return Json(true, JsonRequestBehavior.AllowGet);
            }
            AddErrors(result);
            return View("Error");
        }

        // Add a user to a role
        [HttpPost]
        [ValidateAntiForgeryToken]

FOODSTATION/Views/ManageAccount/UserDashboard.cshtml
@model FOODSTATION.Models.ViewModels.UserVM

@{
    ViewBag.Title = "User dashboard";
}
<div class="searshInput" style="direction:rtl">
    <input type="text" id="myInput" onkeyup="Searsh('userTable')" placeholder="أدخل أسم للبحث ...">
    <i class="fa-solid fa-magnifying-glass"></i>
</div>

<div class="container" id="_UserPartial" style="direction:rtl">
    @Html.Partial("_UserPartial")
</div>

<!--Add User -->

<div class="modal fade User" id="Modal-AddUser">
    @Html.Partial("_AddUser")
</div>

<!--Edit User -->

<div class="modal fade User" id="Modal-EditUser">
    @Html.Partial("_EditUser")
</div>

@section Scripts
{
    @{
        Html.RenderPartial("_AuthScriptsPartial");
        Html.RenderPartial("_ValidationScriptsPartial");
    }
}

FOODSTATION/Views/ManageAccount/_AddUser.cshtml
@model FOODSTATION.Models.ViewModels.UserVM

<div class="modal-dialog">
        <div class="modalContent">
            <div class="modal-header">
                <h2 class="modal-title" style="text-align:center">بيانات الحساب</h2>
                <div class="loading"></div>
            </div>
            <div id="alert_placeholder_addUser">
            </div>
            <div class="modal-body">
                @using (Html.BeginForm("AddNewUser", "ManageAccount", FormMethod.Post, new { enctype = "multipart/form-data", @id = "AddUserForm" }))
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary("", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.RegistrationInValid)
                    <div class="row">
                        <div class="form-horizontal" style="margin-top:50px">
                            <div class="col-md-8 col-md-offset-2">

                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                <div class="form-group">
                                    @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-4", @style = "float:right" })
                                    <div class="col-md-8" style="float:right">
                                        @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "input-fild", @id = "CUuserName", @name = "UserName" } })
                                    </div>
                                </div>
                                <div class="form-group">
                                    @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-4", @style = "float:right" })
                                    <div class="col-md-8" style="float:right">
                                        @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "input-fild", @id = "CUemil", @name = "Email" } })
                                        @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="form-group">
                                    @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-4", @style = "float:right" })
                                    <div class="col-md-8" style="float:right">
                                        @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "input-fild", @id = "CUphoneNumber", @name = "PhoneNumber" } })
                                        @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="form-group">
                                    @Html.LabelFor(model => model.Role, htmlAttributes: new { @class = "control-label col-md-4", @style = "float:right" })
                                    <div class="col-md-8" style="float:right">
                                        @Html.DropDownList("Roles", null, htmlAttributes: new { @class = "input-fild", @name = "Role" })
                                        @Html.ValidationMessageFor(model => model.Role, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="form-group">
                                    @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-4", @style = "float:right" })
                                    <div class="col-md-8" style="float:right">
                                        @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "input-fild", @id = "CUpassword", @name = "Password" } })
                                        @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="form-group">
                                    @Html.LabelFor(model => model.ConfirmPassword, htmlAttributes: new { @class = "control-label col-md-4", @style = "float:right" })
                                    <div class="col-md-8" style="float:right">
                                        @Html.EditorFor(model => model.ConfirmPassword, new { htmlAttributes = new { @class = "input-fild", @id = "CUconfirmpassword", @name = "ConfirmPassword" } })
                                        @Html.ValidationMessageFor(model => model.ConfirmPassword, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                }
            </div>
            <div class="modal-footer">
                <div class="form-group">
                    <div class="col-md-offset-3 col-md-6">
                        <button type="button" id="AddAccount" name="AddAccount" class="btn btn-success modal-BtnCreate">اضافة</button>
                        <button id="btnCreateColse" type="button" class="btn modal-BtnClose" data-dismiss="modal" onclick="resetFilds('AddUserForm',event)">أغلاق</button>
                    </div>
                </div>
            </div>
        </div>
    </div>

FOODSTATION/Views/ManageAccount/_EditUser.cshtml
@model FOODSTATION.Models.ViewModels.UserVM

<div class="modal-dialog">
    <div class="modalContent">
        <div class="modal-header">
            <h2 class="modal-title" style="text-align:center">بيانات الحساب</h2>
            <div class="loading"></div>
        </div>
        <div id="alert_placeholder_editUser">
        </div>
        <div class="modal-body">
            @using (Html.BeginForm("EditUser", "ManageAccount", FormMethod.Post, new { enctype = "multipart/form-data", @id = "EditUserForm" }))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary("", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.RegistrationInValid)
                <div class="row">
                    <div class="form-horizontal" style="margin-top:50px">
                        <div class="col-md-8 col-md-offset-2">

                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            <input type="hidden" name="Id" id="hiddenId" />
                            <div class="form-group">
                                @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-4", @style = "float:right" })
                                <div class="col-md-8" style="float:right">
                                    @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "input-fild", @id = "EUuserName", @name = "UserName" } })
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-4", @style = "float:right" })
                                <div class="col-md-8" style="float:right">
                                    @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "input-fild", @id = "EUemil", @name = "Email" } })
                                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-4", @style = "float:right" })
                                <div class="col-md-8" style="float:right">
                                    @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "input-fild", @id = "EUphoneNumber", @name = "PhoneNumber" } })
                                    @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.Role, htmlAttributes: new { @class = "control-label col-md-4", @style = "float:right" })
                                <div class="col-md-8" style="float:right">
                                    @Html.DropDownList("Roles", null, htmlAttributes: new { @class = "input-fild", @id = "EUrole", @name = "Role" })
                                    @Html.ValidationMessageFor(model => model.Role, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-4", @style = "float:right" })
                                <div class="col-md-8" style="float:right">
                                    @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "input-fild", @id = "EUpassword", @name = "Password" } })
                                    @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.ConfirmPassword, htmlAttributes: new { @class = "control-label col-md-4", @style = "float:right" })
                                <div class="col-md-8" style="float:right">
                                    @Html.EditorFor(model => model.ConfirmPassword, new { htmlAttributes = new { @class = "input-fild", @id = "EUconfirmpassword", @name = "ConfirmPassword" } })
                                    @Html.ValidationMessageFor(model => model.ConfirmPassword, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
        <div class="modal-footer">
            <div class="form-group">
                <div class="col-md-offset-3 col-md-6">
                    <button type="button" id="EditAccount" name="EditAccount" class="btn btn-success modal-BtnCreate">تعديل</button>
                    <button id="btnCreateColse" type="button" class="btn modal-BtnClose" data-dismiss="modal" onclick="resetFilds('EditUserForm',event)">أغلاق</button>
                </div>
            </div>
        </div>
    </div>
</div>

FOODSTATION/Views/ManageAccount/_UserPartial.cshtml
<div>
    <h2>قائمة الحسابات </h2>
</div>
<div>
    <p>
        <a href="#" class="btn btn-primary" data-toggle="modal" data-target="#Modal-AddUser">أضافة حساب</a>
    </p>
</div>
<table class="table" id="userTable">
    <tr class="btn-primary">
        <th>أسم المستخدم</th>
        <th>الإيميل</th>
        <th>رقم الهاتف</th>
        <th>الصلاحية</th>
        <th></th>
    </tr>
    @foreach (var user in ViewBag.Users)
    {
        <tr>
            <td>@user.UserName</td>
            <td>@user.Email</td>
            <td>@user.PhoneNumber</td>
            <td>@user.Role</td>
            <td>
                <a style="font-size:20px" onclick="EditUserConfirm('@user.Id')"><i class="fa-solid fa-pen-to-square Action-Icon" style="color: #005eff;"></i></a> |
                <a style="font-size:20px" onclick="DeleteUserConfirm('@user.Id')"><i class="fa-solid fa-trash-can Action-Icon" style="color: #ff2600;"></i></a>
                <input type="hidden" id="userId" />
            </td>
        </tr>
    }
</table>